const translations = {
    en: {
        "nav-home": "Home",
        "nav-menu": "Menu",
        "nav-about": "About",
        "nav-contact": "Contact",
        "hero-title": "Cloud Fluff 9",
        "hero-subtitle": "Physics-Based Condensed Matter Souffle",
        "hero-cta": "View Menu",
        "hero-cta2": "Make a Reservation",
        "intro-title": "Why Cloud Fluff 9?",
        "intro-1-title": "Physics-Based Fluff",
        "intro-1-desc": "Our recipes are calculated to the molecular level for optimal structural integrity and maximum fluffiness through precise oxide thin film theories.",
        "intro-2-title": "Dorm 9 Exclusive",
        "intro-2-desc": "Located in the legendary Kitchen of Dormitory 9, a culinary sanctuary where science meets gastronomy in an intimate setting.",
        "intro-3-title": "Chef's Expertise",
        "intro-3-desc": "Cooked by a PhD candidate specializing in Condensed Matter Physics. When not in the lab, perfecting the art of souffle pancakes.",
        "team-title": "Our Team",
        "team-chief": "Eunjo Ryoo",
        "team-chief-desc": "Head Chef & Founder",
        "team-chief-bio": "PhD Candidate in Condensed Matter Physics. Swapped oxide thin-film superlattices for soufflé microbubble structures. \"When hot passion meets cold science, the enchantment is born.\"",
        "team-assi1": "Haer Roung Park",
        "team-assi1-desc": "Sous Chef",
        "team-assi1-bio": "Topological soliton control specialist for egg white convection.",
        "team-assi2": "Keon Woong Park",
        "team-assi2-desc": "Kitchen Assistant",
        "team-assi2-bio": "Molecular whipping alignment designer using Coherent Population Trapping.",
        "team-assi3": "Sanghyeon Kim",
        "team-assi3-desc": "Kitchen Staff",
        "team-assi3-bio": "Fluid viscosity and flow monitoring expert using ferroelectric switching models.",
        "menu-section-title": "Our Signature Menu",
        "menu-item-title": "Epitaxial Grown Egg Souffle Pancake",
        "menu-item-desc": "Egg white foams and sugar particles engineered in perfect symmetry, capturing the fundamental interactions of breakfast.",
        "menu-item-price": "₩ 15,000",
        "menu-explore": "Explore Full Menu",
        "experience-title": "Experience Cloud Fluff 9",
        "experience-subtitle": "Join us at Dorm 9 Kitchen for an unforgettable culinary journey where science and taste collide.",
        "book-table": "Book Your Table",
        "menu-title": "The Menu",
        "menu-intro": "A carefully curated selection of souffles, each a masterpiece of scientific precision and culinary artistry.",
        "menu-experimental": "The Experimental Blend",
        "menu-experimental-desc": "A daring combination of traditional souffle with modern ingredient variations. This item changes seasonally based on the chef's latest lab experiments and available premium ingredients.",
        "menu-limited": "Limited availability - Ask our staff for current variation",
        "menu-experimental-price": "₩ 14,000",
        "menu-legendary": "The Legendary Fusion",
        "menu-legendary-desc": "A groundbreaking creation that fuses traditional souffle techniques with contemporary plating aesthetics. Served with a side of house-made berry compote and edible flowers for maximum visual impact.",
        "menu-signature": "The signature dish - Requires 24-hour advance reservation",
        "menu-legendary-price": "₩ 18,000",
        "questions-title": "Have Questions About Our Menu?",
        "questions-subtitle": "Contact us to learn more about our dishes, dietary accommodations, or to make a special request.",
        "about-title": "About Cloud Fluff 9",
        "about-subtitle": "Where science meets culinary artistry in the heart of Dormitory 9",
        "our-story": "Our Story",
        "about-p1": "Cloud Fluff 9 emerged from a unique collision of physics research and culinary passion. Our chef, a PhD candidate specializing in Condensed Matter Physics, realized that the principles governing oxide thin films could be applied to creating the perfect souffle.",
        "about-p2": "What started as late-night lab-to-kitchen experiments became a mission: to prove that haute cuisine doesn't require expensive ingredients or pretentious attitudes—just precision, passion, and a deep understanding of the molecular world.",
        "about-p3": "Today, Cloud Fluff 9 stands as a testament to accessible fine dining, where rigorous scientific methodology meets the joy of feeding people extraordinarily delicious food.",
        "precision-meets-passion": "Precision Meets Passion",
        "precision-subtitle": "Every souffle is a work of scientific art, engineered to perfection and served with genuine care.",
        "philosophy-title": "Our Philosophy",
        "quality-first": "Quality First",
        "quality-desc": "We use only the finest ingredients, sourced carefully to ensure every component meets our exacting standards.",
        "scientific-precision": "Scientific Precision",
        "scientific-desc": "Each recipe is tested and refined using rigorous scientific methods, ensuring consistency and perfection.",
        "accessibility": "Accessibility",
        "accessibility-desc": "Fine dining doesn't have to be exclusive. We believe everyone deserves to experience culinary excellence.",
        "join-us": "Join Us at Cloud Fluff 9",
        "join-subtitle": "Experience the convergence of science and cuisine. Reserve your table today.",
        "contact-title": "Visit Us",
        "contact-subtitle": "Located in the heart of Dormitory 9, ready to serve you an unforgettable culinary experience",
        "get-in-touch": "Get in Touch",
        "location": "Location",
        "location-info": "Dormitory 9 Kitchen, POSTECH (Pohang University of Science and Technology), Pohang, South Korea",
        "hours": "Hours",
        "hours-info": "Open when the chef is not in the lab",
        "hours-times": "Typically: Wednesday - Saturday, 6:00 PM - 11:00 PM",
        "hours-note": "Please call to confirm availability",
        "contact-info": "Contact Info",
        "phone": "Phone",
        "email": "Email",
        "ready-title": "Ready to Experience Cloud Fluff 9?",
        "ready-subtitle": "Make a reservation and discover why our guests call it a transcendent dining experience.",
        "seating-pref": "Seating Preference:",
        "academic-phase": "Your Academic / Social Phase:",
        "opt-superposition": "Superposition (Inside & Outside - Collapses when observed)",
        "opt-inside": "Inside State |1⟩ (Highly correlated kitchen air)",
        "opt-outside": "Outside State |0⟩ (Subject to atmospheric entropy)",
        "opt-phd": "PhD Candidate (100% Chef Sympathy, Priority Seat)",
        "opt-prof": "Professor (5x surcharge applied directly to research grant)",
        "opt-outsider": "Non-Physicist / Civilian (highly suspect, friction > 0)",
        "contact-submit": "Contact",
        "gallery-title": "Our Memories",
        "gallery-intro": "A collection of moments from Cloud Fluff 9 - from delicious dishes to unforgettable experiences.",
        "menu-item-1-title": "Epitaxial Grown Egg Souffle Pancake",
        "menu-item-1-desc": "Egg white foams and sugar particles engineered in perfect symmetry, capturing the fundamental interactions of breakfast.",
        "menu-item-1-critique": "\"A culinary verification of the Higgs mechanism!\" — Particle Physics Journal",
        "menu-item-2-title": "Uncertainty Principle Pork Belly, Kimchi & Garlic",
        "menu-item-2-desc": "A multi-phase system where the location of pork belly lipids and the momentum of garlic compounds cannot be simultaneously measured.",
        "menu-item-2-critique": "\"We cannot measure how fast this pork disappears!\" — Heisenberg's Grill Master",
        "menu-item-3-title": "Schrödinger's Wavefunction Cabbage Tuna Rice Bowl",
        "menu-item-3-desc": "A superposition of shredded cabbage, canned tuna, and a sunny-side-up egg. The flavor remains unknown until the first bite collapses the wave function.",
        "menu-item-3-critique": "\"A dead and alive flavor at the same time!\" — Quantum Philosopher",
        "menu-item-4-title": "Wave-Particle Duality Egg Fried Rice-Porridge",
        "menu-item-4-desc": "A dish exhibiting dual properties: granular rice particle-like scattering combined with fluid, high-viscosity porridge-like wave flow due to excess moisture.",
        "menu-item-4-critique": "\"A perfect demonstration of fluid-particle duality!\" — Modern Food Theorist",
        "menu-item-5-title": "Thermal Equilibrium Stir-Fried Dumplings",
        "menu-item-5-desc": "Pork dumplings pan-fried at high temperatures, achieving absolute thermal and chemical equilibrium with hot chili oil and seasoned chives.",
        "menu-item-5-critique": "\"Maximized flavor entropy at absolute thermal stability!\" — Thermodynamics Gourmet",
        "menu-item-6-title": "Entropy Maximum Pancake with Honey & Banana",
        "menu-item-6-desc": "A chaotic, high-entropy arrangement of sliced banana disks and viscous organic honey molecules randomly dispersed over a simple pancake substrate.",
        "menu-item-6-critique": "\"A beautiful manifestation of the second law!\" — Entropy Preacher",
        "menu-item-7-title": "Photoelectric Threshold Chuck Eye Roll Steak",
        "menu-item-7-desc": "A highly resilient beef lattice requiring an extreme activation energy. Ejects rich beef juices only when hit by a threshold frequency of jaw chewing force.",
        "menu-item-7-critique": "\"Requires an infinite work function to chew!\" — Solid State Dentist",
        "menu-item-8-title": "Superconducting Zero-Friction Chapagetti",
        "menu-item-8-desc": "Black bean noodles in a highly viscous dark matter sauce, topped with a fried egg. Ingestion occurs with zero friction, flowing like a supercurrent of pure joy.",
        "menu-item-8-critique": "\"Flows through the digestive tract with zero friction!\" — Low-Temperature Physicist",
        "menu-item-9-title": "Bose-Einstein Condensation Kimchi Fried Rice",
        "menu-item-9-desc": "Overnight-preserved rice grains, kimchi bits, and oil molecules condensed into a singular, homogeneous quantum state of pure red flavor.",
        "menu-item-9-critique": "\"Every grain behaves as a single coherent quantum wave!\" — Statistical Mechanics Chef",
        "menu-item-10-title": "11-Dimensional String Theory Spicy Stir-Fried Beef",
        "menu-item-10-desc": "Sliced beef chuck eye roll in spicy pepper paste, vibrating at various frequencies in an 11-dimensional space to simulate the flavor profile of pork jeyuk.",
        "menu-item-10-critique": "\"A beautiful simulation of jeyuk using a beef lattice!\" — String Theorist",
        "menu-item-11-title": "Big Bang Expansion Cabbage Shrimp Rice Bowl",
        "menu-item-11-desc": "An expanding hot universe of flavor created from a garlic oil singularity, exploding with white cabbage gas and shrimp particles over a white rice vacuum.",
        "menu-item-11-critique": "\"The culinary expansion of the early universe!\" — Cosmological Diner",
        "menu-item-12-title": "High-Temperature Plasma Chive Egg Stir-Fry",
        "menu-item-12-desc": "A high-temperature scrambled egg matrix embedded with green chives and shrimp, representing peak thermodynamic entropy and highly ionized plasma gas.",
        "menu-item-12-critique": "\"All gastronomers agree, this plasma state is fully ionized!\" — High-Energy Warden",
        "menu-item-13-title": "Quantum Entangledkimchi Fried Rice",
        "menu-item-13-desc": "A highly correlated, two-component quantum system consisting of red kimchi particles and cured ham blocks, stir-fried to preserve entanglement.",
        "menu-item-13-critique": "\"A flavor resonance that violates Bell's inequality!\" — The Quantum Gastronomist"
    },
    kr: {
        "nav-home": "홈",
        "nav-menu": "메뉴",
        "nav-about": "소개",
        "nav-contact": "문의",
        "hero-title": "Cloud Fluff 9",
        "hero-subtitle": "물리학 기반 응집물질 수플레",
        "hero-cta": "메뉴 보기",
        "hero-cta2": "예약하기",
        "intro-title": "왜 Cloud Fluff 9인가?",
        "intro-1-title": "물리학 기반 폭신함",
        "intro-1-desc": "분자 수준까지 계산된 레시피로 최적의 구조적 안정성과 산화물 박막 이론을 통한 극대화된 폭신함을 자랑합니다.",
        "intro-2-title": "9동 기숙사 전용",
        "intro-2-desc": "전설적인 9동 기숙사 주방에 위치한 요리 성지에서 과학과 미각의 조화를 경험하세요.",
        "intro-3-title": "박사과정의 손맛",
        "intro-3-desc": "응집물질물리를 전공하는 박사과정 학생이 직접 요리합니다. 랩실에 없을 때 수플레 팬케이크를 완성해갑니다.",
        "team-title": "저희 팀",
        "team-chief": "류은조",
        "team-chief-desc": "수석 셰프 & 창업자",
        "team-chief-bio": "응집물질물리 박사과정 연구원으로, 산화물 초격자 박막 접합 연구실에서 쌓아올린 노하우를 바탕으로 수플레 내부 기포 대류를 설계합니다. \"뜨거운 열정과 차가운 과학이 만나 마법이 탄생합니다.\"",
        "team-assi1": "박해룡",
        "team-assi1-desc": "수 셰프",
        "team-assi1-bio": "위상 솔리톤 제어를 통한 계란 거품 대류 통제 전문가.",
        "team-assi2": "박건웅",
        "team-assi2-desc": "주방 어시스턴트",
        "team-assi2-bio": "결맞음 포획 상태를 활용한 분자 수준의 휘핑 정렬 담당.",
        "team-assi3": "김상현",
        "team-assi3-desc": "주방 스태프",
        "team-assi3-bio": "강유전체 스위칭 이론을 응용한 반죽 점도 유동성 모니터링 담당.",
        "menu-section-title": "시그니처 메뉴",
        "menu-item-title": "에피택셜 성장 에그 수플레 팬케이크",
        "menu-item-desc": "계란 흰자 거품과 설탕 입자의 완벽한 대칭적 구성으로 조화로운 맛의 기본입자 작용을 선보입니다.",
        "menu-item-price": "₩ 15,000",
        "menu-explore": "전체 메뉴 보기",
        "experience-title": "Cloud Fluff 9를 경험하세요",
        "experience-subtitle": "9동 기숙사 주방에서 과학과 맛이 만나는 잊을 수 없는 요리 여행을 함께하세요.",
        "book-table": "테이블 예약하기",
        "menu-title": "메뉴",
        "menu-intro": "과학적 정밀도와 요리 예술성의 걸작인 수플레들의 엄선된 컬렉션입니다.",
        "menu-experimental": "실험적 블렌드",
        "menu-experimental-desc": "전통 수플레 기법과 현대 재료의 대담한 조합입니다. 이 메뉴는 셰프의 최신 랩 실험과 프리미엄 재료 가용성에 따라 계절마다 변합니다.",
        "menu-limited": "한정 제공 - 현재 메뉴 변형에 대해 스태프에게 문의하세요",
        "menu-experimental-price": "₩ 14,000",
        "menu-legendary": "전설의 퓨전",
        "menu-legendary-desc": "전통 수플레 기법과 현대적 플레이팅 미학을 융합한 혁신적인 창작물입니다. 집에서 만든 베리 콤포트와 먹을 수 있는 꽃으로 함께 제공됩니다.",
        "menu-signature": "시그니처 메뉴 - 24시간 전 예약 필수",
        "menu-legendary-price": "₩ 18,000",
        "questions-title": "메뉴에 대한 질문이 있으신가요?",
        "questions-subtitle": "요리에 대해 더 알아보거나 식이 요건을 고려하거나 특별 요청을 하려면 저희에게 연락하세요.",
        "about-title": "Cloud Fluff 9 소개",
        "about-subtitle": "기숙사 9동 중심부에서 과학과 요리 예술이 만나는 곳",
        "our-story": "저희 이야기",
        "about-p1": "Cloud Fluff 9는 물리학 연구와 요리에 대한 열정이 만나 탄생했습니다. 응집물질물리를 전공하는 박사과정 학생인 저희 셰프는 산화물 박막을 지배하는 원리가 완벽한 수플레 만드는 데 적용될 수 있다는 것을 깨달았습니다.",
        "about-p2": "늦은 밤 랩실에서 주방으로의 실험들은 하나의 미션으로 발전했습니다: 고급 요리가 비싼 재료나 거만한 태도가 아닌 정밀성, 열정, 분자 세계에 대한 깊은 이해만 필요하다는 것을 증명하는 미션입니다.",
        "about-p3": "오늘 Cloud Fluff 9는 엄격한 과학적 방법론이 사람들에게 맛있는 음식을 제공하는 기쁨과 만나는 접근성 높은 미식 경험의 증거입니다.",
        "precision-meets-passion": "정밀함이 열정을 만나다",
        "precision-subtitle": "모든 수플레는 과학 예술 작품으로, 완벽함을 추구하고 진심 어린 배려로 제공됩니다.",
        "philosophy-title": "저희 철학",
        "quality-first": "품질 우선",
        "quality-desc": "우리는 최고 품질의 재료만을 사용하며, 모든 요소가 엄격한 기준을 충족하도록 신중하게 선별합니다.",
        "scientific-precision": "과학적 정밀성",
        "scientific-desc": "각 레시피는 엄격한 과학적 방법으로 테스트하고 개선되어 일관성과 완벽함을 보장합니다.",
        "accessibility": "접근성",
        "accessibility-desc": "미식은 독점적일 필요가 없습니다. 모든 사람이 요리의 우수성을 경험할 자격이 있다고 믿습니다.",
        "join-us": "Cloud Fluff 9에 참여하세요",
        "join-subtitle": "과학과 요리의 수렴을 경험하세요. 오늘 테이블을 예약하세요.",
        "contact-title": "오시는 길",
        "contact-subtitle": "기숙사 9동 중심부에 위치하여 잊을 수 없는 요리 경험을 제공할 준비가 되어 있습니다",
        "get-in-touch": "연락처",
        "location": "위치",
        "location-info": "포항공과대학교(POSTECH) 기숙사 9동 주방, 포항, 대한민국",
        "hours": "영업 시간",
        "hours-info": "셰프가 랩실에 없을 때 영업",
        "hours-times": "일반적으로: 수요일-토요일, 오후 6시-11시",
        "hours-note": "가용성 확인 시 전화 부탁드립니다",
        "contact-info": "연락처",
        "phone": "전화",
        "email": "이메일",
        "ready-title": "Cloud Fluff 9를 경험할 준비가 되셨나요?",
        "ready-subtitle": "예약을 하고 저희 손님들이 초월적인 식사 경험이라고 부르는 이유를 발견하세요.",
        "seating-pref": "좌석 선호도:",
        "academic-phase": "학술적 / 사회적 상태:",
        "opt-superposition": "중첩 상태 (내부 & 외부 - 관측 시 즉시 붕괴)",
        "opt-inside": "내부 상태 |1⟩ (상호 연관도 높은 주방 공기)",
        "opt-outside": "외부 상태 |0⟩ (대기 엔트로피의 영향)",
        "opt-phd": "박사과정 대학원생 (셰프와 동병상련 100%, 우선 좌석 배정)",
        "opt-prof": "지도교수 (연구과제 카드에서 직접 5배 할증 청구)",
        "opt-outsider": "비물리학자 / 외부인 (마찰력 > 0, 매우 수상함)",
        "contact-submit": "연락하기",
        "gallery-title": "우리의 추억들",
        "gallery-intro": "Cloud Fluff 9의 순간들 모음 - 맛있는 요리부터 잊을 수 없는 경험까지.",
        "menu-item-1-title": "에피택셜 성장 에그 수플레 팬케이크",
        "menu-item-1-desc": "계란 흰자 거품과 설탕 입자의 완벽한 대칭적 구성으로 조화로운 맛의 기본입자 작용을 선보이는 과학적인 에그 수플레 팬케이크.",
        "menu-item-1-critique": "\"맛의 힉스 메커니즘을 입증하다!\" - 입자물리학 저널",
        "menu-item-2-title": "불확정성 원리 삼겹살 김치 마늘 구이",
        "menu-item-2-desc": "고온 마찰 불판에서 조리되는 삼겹살 지질의 위치와 마늘 화합물의 운동량을 동시에 측정할 수 없는 혼돈의 다상계(multi-phase system) 구이 요리.",
        "menu-item-2-critique": "\"삼겹살이 사라지는 속도를 전혀 측정할 수 없다!\" - 양자요리학자",
        "menu-item-3-title": "슈뢰딩거 파동함수 양배추 참치 덮밥",
        "menu-item-3-desc": "신선하게 썬 양배추와 참치캔, 그리고 반숙 계란 후라이가 결맞음 상태로 공존하는 덮밥. 첫 입을 씹기 전까지는 맛의 파동함수가 붕괴되지 않습니다.",
        "menu-item-3-critique": "\"먹기 전까지는 알 수 없는 양자역학적 신비!\" - 양자철학자",
        "menu-item-4-title": "이중성 계란볶음밥-죽",
        "menu-item-4-desc": "고슬고슬한 밥알 입자의 산란성과 수분 통제 실패로 인한 파동성(거의 죽에 가까운 유동성)을 동시에 지닌 기묘한 이중성의 계란볶음밥.",
        "menu-item-4-critique": "\"유체역학과 양자역학의 기묘한 타협!\" - 현대미식가",
        "menu-item-5-title": "열평형 만두볶음",
        "menu-item-5-desc": "고온의 팬에서 볶아진 바삭한 고기만두와 매콤한 고추기름, 아삭한 부추가 열과 질량이 완벽하게 동등하게 결합된 평형 상태의 만두볶음.",
        "menu-item-5-critique": "\"절대 평형 온도에서 달성된 극도의 맛 엔트로피!\" - 열역학 미식가",
        "menu-item-6-title": "엔트로피 극대화 허니 바나나 팬케이크",
        "menu-item-6-desc": "소박한 팬케이크 기질 위에 바나나 디스크 슬라이스와 고점도 꿀 분자들이 완전한 무질서 상태로 랜덤 분산된 고엔트로피 스택.",
        "menu-item-6-critique": "\"우주 팽창과 엔트로피 법칙의 아름다운 단맛!\" - 엔트로피 전도사",
        "menu-item-7-title": "광전효과 한계 척아이롤 스테이크",
        "menu-item-7-desc": "고도의 구조적 활성화 에너지(턱 운동)를 필요로 하는 강력한 소고기 격자 스테이크. 고무창보다 질긴... 턱관절 한계 임계값을 시험하는 척아이롤 구이.",
        "menu-item-7-critique": "\"임계 자극에서만 비출되는 육즙! 씹기 위해 무한한 일함수가 요구됨.\" - 광학 미식가",
        "menu-item-8-title": "초전도 제로 마찰 짜파게티",
        "menu-item-8-desc": "고점도 짜장 소스와 윤기 흐르는 면발, 그 위의 계란 후라이가 마찰 저항 제로에 수렴하는 완벽한 유동 상태를 형성하여 저항이 없는 흡입의 짜파게티.",
        "menu-item-8-critique": "\"새벽 2시에 저항 없이 무한히 흡입되는 초전도 현상!\" - 저온물리학자",
        "menu-item-9-title": "보스-아인슈타인 응축 김치볶음밥",
        "menu-item-9-desc": "개별 입자(밥알, 김치, 참기름)들이 밤샘 보존 과정을 거치며 하나의 단일한 미각적 결맞음(coherence) 상태로 응축된 완벽한 일체형 김치볶음밥.",
        "menu-item-9-critique": "\"모든 밥알이 단 하나의 거대한 붉은 맛의 파동으로 춤춘다!\" - 양자통계학 전문가",
        "menu-item-10-title": "11-차원 초끈이론 매콤 소고기 볶음",
        "menu-item-10-desc": "초고온 고추장 양념 속에서 소고기 슬라이스들이 11차원 초끈처럼 진동하며, 저렴하게 제육볶음의 맛을 정밀하게 모사하는 현대 입자물리학의 걸작 요리.",
        "menu-item-10-critique": "\"싸구려 척아이롤이 제육볶음의 현을 튕긴다!\" - 끈이론 미식가",
        "menu-item-11-title": "빅뱅 팽창 양배추 새우 덮밥",
        "menu-item-11-desc": "달궈진 마늘기름 특이점에서 시작된 팽창 우주 모델. 아삭한 양배추 가스와 고에너지 새우 입자들이 흰 쌀밥 진공 위에 고르게 안착한 양배추 새우 덮밥.",
        "menu-item-11-critique": "\"한 그릇에 담긴 초기 우주의 대폭발 팽창!\" - 우주론 미식가",
        "menu-item-12-title": "고온 플라스마 부추계란 볶음",
        "menu-item-12-desc": "분자들의 불규칙한 브라운 운동과 열역학적 무질서(엔트로피)를 극대화하고 프라이팬 내부의 고온 플라스마 상태를 모사한 부추계란 볶음.",
        "menu-item-12-critique": "\"이것은 미식인가, 아니면 열역학적 재앙인가?\" - 9동 기숙사 사감",
        "menu-item-13-title": "양자 얽힘 김치볶음밥",
        "menu-item-13-desc": "붉은 김치 입자와 잘게 썬 햄 블록으로 구성된 고도 상관 이체계(two-body system). 팬 위에서 강력하게 커플링된 상태를 유지하는 기숙사식 김치볶음밥.",
        "menu-item-13-critique": "\"벨의 부등식을 위배하는 맛의 얽힘!\" - 양자미식가"
    }
};
